
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/lukee/toolchains/Cmake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
